# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'ShuffleBoardApp' do
  pod "FastttCamera"
  pod "AFNetworking", "~> 2.0"
end

target 'ShuffleBoardAppTests' do

end

target 'ShuffleBoardAppUITests' do

end

